##config_op mul -impl dsp
##config_op add -impl dsp
##config_op sub -impl dsp
config_op fadd -impl fulldsp
config_op fsub -impl fulldsp
##config_op fdiv -impl dsp
config_op fexp -impl fulldsp
config_op flog -impl fulldsp
config_op fmul -impl fulldsp
config_op frsqrt -impl fulldsp
config_op frecip -impl fulldsp
##config_op fsqrt -impl fulldsp
##config_op facc -impl fulldsp
##config_op fmacc -impl fulldsp
##config_op fmadd -impl fulldsp
